### ISSUE TITLE
crash when trying to move player

### ISSUE THREAD

**Issue by PandaBoy444** [rwtema/FunkyLocomotion#130]
Game crashes when moving a player with frames, tested in a clean environment (only funky locomotion and thermal expansions to power to movers).
[crash report](https://github.com/rwtema/FunkyLocomotion/files/2020391/crash-2018-05-20_17.11.24-server.txt)
[log](https://github.com/rwtema/FunkyLocomotion/files/2020392/latest.log)

**Comment by weeryan17** [comment]
I got this same problem, and just to help you out here is the exact error
https://hastebin.com/ilopiyexiq.css
It appears `net.minecraft.entity.Entity#isCollidedHorizontally` doesn't exists.
I'm running forge version 14.23.3.2669 I'll update and see if that fixes stuff

**Comment by smithb99** [comment]
I think you're going in the opposite direction. The mod was compiled against Forge 14.23.0.2529, an earlier version.  From looking at the sources on the more up-to-date versions of Forge, `net.minecraft.entity.Entity#isCollidedHorizontally` does not exist anymore, because it has been renamed to `net.minecraft.entity.Entity#collidedHorizontally` which would throw a NoSuchFieldError. If anyone is more skilled with Forge than I, it seems like it would be a pretty simple PR to throw together.
